name: Angular CI

on:
  push:
    branches: [ page-source ]
  pull_request:
    branches: [ page-source ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Seting up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Installing Angular
      run: npm install -g @angular/cli
      
    - name: npm install
      run: npm install
    - name: Production build
      run: ng build --prod --base-href https://samolego.github.io/LangCards/
    - name: Providing 404 page
      run: cp docs/index.html docs/404.html
    - name: Github Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: docs/
